/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpack;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Farhan Nasir
 */
public class BusBook extends javax.swing.JFrame {

    /**
     * Creates new form BusBook
     */
    public BusBook() {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
    }
    
    public BusBook(String from,String to,String bnm) {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
        busfrom.setText(from);
        busfrom.setEditable(false);
        busto.setText(to);
        busto.setEditable(false);
        namebus.setText(bnm);
        namebus.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        detailstitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        busto = new javax.swing.JTextField();
        busfrom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namebus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        confirmbus = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(58, 104, 233));
        jPanel3.setMaximumSize(new java.awt.Dimension(700, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailstitle.setBackground(new java.awt.Color(255, 255, 255));
        detailstitle.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        detailstitle.setForeground(new java.awt.Color(255, 255, 255));
        detailstitle.setText("Bus Ticket Booking");
        jPanel3.add(detailstitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 330, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("From:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("To:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 30, 40));

        busto.setBackground(new java.awt.Color(204, 204, 255));
        busto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        busto.setText("jTextField1");
        jPanel1.add(busto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 270, -1));

        busfrom.setBackground(new java.awt.Color(204, 204, 255));
        busfrom.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        busfrom.setText("jTextField1");
        jPanel1.add(busfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Bus Service:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, 40));

        namebus.setBackground(new java.awt.Color(204, 204, 255));
        namebus.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        namebus.setText("jTextField1");
        jPanel1.add(namebus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Select Number of Persons: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 190, 40));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose number", "1", "2", "3", "4", "5", "6" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Fare:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 40, 40));

        fare.setBackground(new java.awt.Color(204, 204, 255));
        fare.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(fare, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 270, -1));

        confirmbus.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        confirmbus.setText("Confirm");
        confirmbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbusActionPerformed(evt);
            }
        });
        jPanel1.add(confirmbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbusActionPerformed
        // TODO add your handling code here:
        JFrame msg = new JFrame();
        JOptionPane.showMessageDialog(msg, "Ticket Booked Successfully");
        dispose();
    }//GEN-LAST:event_confirmbusActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        fare.setText("XXXX Taka");
        fare.setEditable(false);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busfrom;
    private javax.swing.JTextField busto;
    private javax.swing.JButton confirmbus;
    private javax.swing.JLabel detailstitle;
    private javax.swing.JTextField fare;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField namebus;
    // End of variables declaration//GEN-END:variables
}
