package projectpack;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

public class BusRoutes extends javax.swing.JFrame {

    private int fromind, toind, cnt = 0;
    private HashMap<Integer, ArrayList<String>> touristplace;
    private HashMap<String, String> placename;
    private HashMap<Integer, ArrayList<String>> hotelname;
    private HashMap<customPair, ArrayList<String>> busname;

    /**
     * Creates new form BusRoutes
     */
    public BusRoutes() {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
    }

    public BusRoutes(HashMap<Integer, ArrayList<String>> tpname, HashMap<String, String> pname, HashMap<Integer, ArrayList<String>> hname, HashMap<customPair, ArrayList<String>> bname, int sti, int di) {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
        fromind = sti;
        toind = di;
        touristplace = tpname;
        hotelname = hname;
        busname = bname;
        placename = pname;
        load();
    }

    private void load() {
        FromTOPanel ftp = new FromTOPanel();
        scpane.add(ftp);
        scpane.revalidate();
        scpane.repaint();
        ftp.setFromTo(fromind, toind);
        int mini = Math.min(fromind, toind);
        int maxi = Math.max(fromind, toind);
        String fpath = Integer.toString(mini) + Integer.toString(maxi);
        System.out.println(fpath);
        try {
            FileReader fr = new FileReader("src\\Files\\" + fpath + ".txt");
            BufferedReader fbr = new BufferedReader(fr);
            String allbus = "";
            int i;
            try {
                while ((i = fbr.read()) != -1) {

                    allbus += (char) i;
                }
                System.out.println(allbus);
                String[] sepbus = allbus.split(";");

                int n = sepbus.length;

                HotelBookPanel hbp[] = new HotelBookPanel[n];
                scpane.setPreferredSize(new Dimension(scpane.getWidth(), 50 + n * 100));
                scpane.revalidate();
                scpane.repaint();
                
                
                String[] names  = {"Choose Start Location","Dhaka","Chattogram","Cox's Bazar","Sylhet","Bandonban","Rangamati","Kuakata"};

                for (i = 0; i < n; i++) {
                    hbp[i] = new HotelBookPanel(names[fromind],names[toind]);
                    if (cnt % 2 == 1) {
                        hbp[i].setWhite();
                    }
                    cnt++;
                    //hbp[i].setPanelTilte(hotelname.get(toind).get(i));
                    hbp[i].setPanelTilte(sepbus[i]);
                    scpane.add(hbp[i]);
                    scpane.revalidate();
                    scpane.repaint();
                }

            } catch (IOException ex) {
                Logger.getLogger(BusRoutes.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BusRoutes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scpane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bustotour = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bustohotel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bustoprofile = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 104, 233));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Available Buses");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 530, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        scpane.setBackground(new java.awt.Color(255, 255, 255));
        scpane.setMaximumSize(new java.awt.Dimension(530, 1000));
        scpane.setMinimumSize(new java.awt.Dimension(530, 300));
        scpane.setPreferredSize(new java.awt.Dimension(530, 1000));
        scpane.setLayout(new javax.swing.BoxLayout(scpane, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(scpane);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 530, 350));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 530, 430));

        jPanel1.setBackground(new java.awt.Color(8, 49, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(8, 49, 64));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        bustotour.setBackground(new java.awt.Color(8, 49, 64));
        bustotour.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        bustotour.setForeground(new java.awt.Color(255, 255, 255));
        bustotour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bustotour.setText("Tourist Attractions");
        bustotour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bustotourMouseClicked(evt);
            }
        });
        jPanel3.add(bustotour);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 40));

        jPanel4.setBackground(new java.awt.Color(8, 72, 87));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bus Routes");
        jPanel4.add(jLabel2);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 40));

        jPanel5.setBackground(new java.awt.Color(8, 49, 64));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        bustohotel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        bustohotel.setForeground(new java.awt.Color(255, 255, 255));
        bustohotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bustohotel.setText("Hotels");
        bustohotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bustohotelMouseClicked(evt);
            }
        });
        jPanel5.add(bustohotel);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        jPanel6.setBackground(new java.awt.Color(8, 49, 64));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        bustoprofile.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        bustoprofile.setForeground(new java.awt.Color(255, 255, 255));
        bustoprofile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bustoprofile.setText("Profile");
        bustoprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bustoprofileMouseClicked(evt);
            }
        });
        jPanel6.add(bustoprofile);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectpack/Images/icons8-back-arrow-30.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bustoprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bustoprofileMouseClicked
        Profile pf = new Profile(touristplace, placename, hotelname, busname, fromind, toind);
        pf.setVisible(true);
        dispose();
    }//GEN-LAST:event_bustoprofileMouseClicked

    private void bustotourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bustotourMouseClicked
        // TODO add your handling code here:
        TourPlaces tr = new TourPlaces(touristplace, placename, hotelname, busname, fromind, toind);
        tr.setVisible(true);
        dispose();
    }//GEN-LAST:event_bustotourMouseClicked

    private void bustohotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bustohotelMouseClicked
        // TODO add your handling code here:
        Hotels ht = new Hotels(touristplace, placename, hotelname, busname, fromind, toind);
        ht.setVisible(true);
        dispose();
    }//GEN-LAST:event_bustohotelMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        Destination_new dn = new Destination_new(fromind, toind);
        dn.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } else {
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusRoutes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bustohotel;
    private javax.swing.JLabel bustoprofile;
    private javax.swing.JLabel bustotour;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel scpane;
    // End of variables declaration//GEN-END:variables
}
