package projectpack;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DetailsWindow extends javax.swing.JFrame {

    private String filepath;

    /**
     * Creates new form DetailsWindow
     */
    public DetailsWindow() {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
        detailsbox.setEditable(false);
    }

    public DetailsWindow(String pathv, String title) {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
        detailsbox.setEditable(false);
        filepath = pathv;
        detailstitle.setText(title);
        detailsbox.setLineWrap(true);
        loadText();
    }

    private void loadText() {
        FileReader fr;
        try {
            fr = new FileReader("src\\Files\\" + filepath);
            BufferedReader br = new BufferedReader(fr);
            int i;
            try {
                while ((i = br.read()) != -1) {
                    String tmp = "";
                    tmp+=(char)i;
                    detailsbox.append(tmp);
                }
//                    String thline = null;
//                   while((thline = br.readLine())!=null)
//                   {
//                       detailsbox.append(thline);
//                   }
            } catch (IOException ex) {
                Logger.getLogger(DetailsWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DetailsWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        detailstitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailsbox = new javax.swing.JTextArea();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(58, 104, 233));
        jPanel3.setMaximumSize(new java.awt.Dimension(700, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailstitle.setBackground(new java.awt.Color(255, 255, 255));
        detailstitle.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        detailstitle.setForeground(new java.awt.Color(255, 255, 255));
        detailstitle.setText("Available Hotels");
        jPanel3.add(detailstitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        detailsbox.setColumns(20);
        detailsbox.setRows(5);
        jScrollPane3.setViewportView(detailsbox);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea detailsbox;
    private javax.swing.JLabel detailstitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
