package projectpack;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;

public class Hotels extends javax.swing.JFrame {

    private int fromind, toind, cnt = 0;
    private HashMap<Integer, ArrayList<String>> touristplace;
    private HashMap<String, String> placename;
    private HashMap<Integer, ArrayList<String>> hotelname;
    private HashMap<customPair, ArrayList<String>> busname;

    /**
     * Creates new form Hotels
     */
    public Hotels() {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
    }

    public Hotels(HashMap<Integer, ArrayList<String>> tpname, HashMap<String, String> pname, HashMap<Integer, ArrayList<String>> hname, HashMap<customPair, ArrayList<String>> bname, int sti, int di) {
        initComponents();
        setTitle("Tour in Bangladesh");
        setLocationRelativeTo(null);
        fromind = sti;
        toind = di;
        touristplace = tpname;
        hotelname = hname;
        busname = bname;
        placename = pname;
        load();
    }

    private void load() {
        FromTOPanel ftp = new FromTOPanel();
        scpane.add(ftp);
        scpane.revalidate();
        scpane.repaint();
        ftp.setFromTo(fromind, toind);

        int n = touristplace.get(toind).size();
        System.out.println(n);

        HotelBookPanel hbp[] = new HotelBookPanel[n];
        scpane.setPreferredSize(new Dimension(scpane.getWidth(), 50 + n * 100));
        scpane.revalidate();
        scpane.repaint();

        for (int i = 0; i < n; i++) {
            hbp[i] = new HotelBookPanel();
            if (cnt % 2 == 1) {
                hbp[i].setWhite();
            }
            cnt++;
            hbp[i].setPanelTilte(hotelname.get(toind).get(i));
            scpane.add(hbp[i]);
            scpane.revalidate();
            scpane.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        hoteltotour = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        profiletab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scpane = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(8, 49, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(8, 49, 64));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        hoteltotour.setBackground(new java.awt.Color(8, 49, 64));
        hoteltotour.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hoteltotour.setForeground(new java.awt.Color(255, 255, 255));
        hoteltotour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoteltotour.setText("Tourist Attractions");
        hoteltotour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoteltotourMouseClicked(evt);
            }
        });
        jPanel3.add(hoteltotour);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 40));

        jPanel4.setBackground(new java.awt.Color(8, 49, 64));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bus Routes");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 40));

        jPanel5.setBackground(new java.awt.Color(8, 72, 87));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotels");
        jPanel5.add(jLabel3);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        jPanel6.setBackground(new java.awt.Color(8, 49, 64));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        profiletab.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        profiletab.setForeground(new java.awt.Color(255, 255, 255));
        profiletab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profiletab.setText("Profile");
        profiletab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profiletabMouseClicked(evt);
            }
        });
        jPanel6.add(profiletab);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 430));

        jPanel2.setBackground(new java.awt.Color(58, 104, 233));
        jPanel2.setMaximumSize(new java.awt.Dimension(530, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(530, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(530, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Available Hotels");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 530, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(530, 1400));
        jPanel7.setMinimumSize(new java.awt.Dimension(530, 1400));
        jPanel7.setPreferredSize(new java.awt.Dimension(530, 1400));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(530, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(530, 1400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(530, 1400));

        scpane.setBackground(new java.awt.Color(255, 255, 255));
        scpane.setMaximumSize(new java.awt.Dimension(530, 1000));
        scpane.setMinimumSize(new java.awt.Dimension(530, 300));
        scpane.setPreferredSize(new java.awt.Dimension(530, 1000));
        scpane.setLayout(new javax.swing.BoxLayout(scpane, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(scpane);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 530, 350));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 530, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profiletabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profiletabMouseClicked
        // TODO add your handling code here:
        Profile pf = new Profile();
        //new Profile().setVisible(true);
        pf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profiletabMouseClicked

    private void hoteltotourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoteltotourMouseClicked
        
        System.out.println("Ball");
        System.out.println(touristplace);
        System.out.println(placename);
        System.out.println(hotelname);
        TourPlaces tpp = new TourPlaces(touristplace, placename, hotelname, busname, fromind, toind);
        
        tpp.setVisible(true);
        //this.setVisible(false);
        dispose();
    }//GEN-LAST:event_hoteltotourMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        BusRoutes br = new BusRoutes();
        br.setInd(fromind, toind);
        br.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hoteltotour;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel profiletab;
    private javax.swing.JPanel scpane;
    // End of variables declaration//GEN-END:variables
}
