
package projectpack;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;


public class TourPlacePanel extends javax.swing.JPanel {

    
    private String path ,head;
    /**
     * Creates new form TourPlacePanel
     */
    public TourPlacePanel() {
        initComponents();
    }
    
    public TourPlacePanel(String paths, String heads) {
        initComponents();
        path = paths;
        head = heads;
    }
    
    public void setWhite()
    {
        background.setBackground(Color.white);
        btnBack.setBackground(Color.white);
    }
    
    public void setPanelTilte(String s)
    {
        title.setText(s);
        //System.out.println(s+ "    st");
        //super.update(this.getGraphics());
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        btnBack = new javax.swing.JPanel();
        detailsbtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        background.setMaximumSize(new java.awt.Dimension(530, 100));
        background.setMinimumSize(new java.awt.Dimension(530, 100));
        background.setPreferredSize(new java.awt.Dimension(530, 100));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setMaximumSize(new java.awt.Dimension(520, 100));
        btnBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsbtn.setText("Details");
        detailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsbtnActionPerformed(evt);
            }
        });
        btnBack.add(detailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        background.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 90, 100));

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(58, 104, 233));
        background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsbtnActionPerformed
        // TODO add your handling code here:
        DetailsWindow dw = new DetailsWindow(path, head);
        dw.setVisible(true);
        
    }//GEN-LAST:event_detailsbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnBack;
    private javax.swing.JButton detailsbtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
